---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
language: bash
manual_evaluation: false
choices: []
goal:
  kind: query_passes
  query: grep "Manejo de Terminal" /home/mumuki/curriculums/curriculum-v5.html
name: Juntando todo
