---
tags: []
layout: input_bottom
editor: code
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal:
  kind: query_passes
  query: test -e curriculum-v5.html
name: "¡Qué copión!"
