---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: 
teacher_info: 
manual_evaluation: false
choices:
- value: "...antes de crear una nueva versión, hacer una copia del archivo, y luego
    modificar esa copia."
  checked: true
- value: "...después de crear una nueva versión, hacer una copia del archivo"
  checked: false
