---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: 
teacher_info: 
manual_evaluation: false
choices:
- value: "...hacer una copia del archivo original, y luego modificar esa copia."
  checked: true
- value: "...modificar el archivo original, y luego hacer una copia."
  checked: false
- value: "...hacer una copia del archivo, luego modificar esa copia, y finalmente
    eliminar el archivo original."
  checked: false
